/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Usuarios;

import Principal.Procesos;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author JL
 */
public class Usuarios_Permisos extends javax.swing.JFrame {

    /**
     * Creates new form Usuarios_Permisos
     */
    public static Statement estSQL=Usuarios.estSQLSys;
    public Usuarios_Permisos() {
        initComponents();
        insertImage();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        this.setLocationRelativeTo(null);
        this.setTitle("Asignar Permisos Usuarios");
        this.setResizable(false);
        cerrar();
        cargarComboUser();
        
    }
     public void cargarComboUser()
    {
        cmbUser.removeAllItems();
        Procesos sql=new Procesos();
        ResultSet rs=sql.consultarDatos(estSQL, "SELECT USERNAME FROM DBA_USERS where username like 'C##%'");
        sql.buscarDatosCombo(rs, cmbUser);
    }
    public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        panel.add(Imagen);
        panel.repaint();
    }
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(590,380);
        }
        @Override
        public void paint(Graphics grafico)
        {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondoMain2.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        insertJug = new javax.swing.JCheckBox();
        selJug = new javax.swing.JCheckBox();
        modifJug = new javax.swing.JCheckBox();
        delJug = new javax.swing.JCheckBox();
        selPart = new javax.swing.JCheckBox();
        selEst = new javax.swing.JCheckBox();
        insertPart = new javax.swing.JCheckBox();
        insertEst = new javax.swing.JCheckBox();
        modifPart = new javax.swing.JCheckBox();
        delPart = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cmbUser = new javax.swing.JComboBox();
        btnAsignar = new javax.swing.JButton();
        txtCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel1.setText("Gestión de Permisos a Usuarios");

        jLabel2.setFont(new java.awt.Font("Calibri Light", 1, 10)); // NOI18N
        jLabel2.setText("Seleccionar Permisos sobre las Tablas:");

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setText("Tabla Jugador: ");

        jLabel4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel4.setText("Tabla Partido:");

        jLabel5.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel5.setText("Estadísticas: ");

        insertJug.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        insertJug.setText("Inserción");

        selJug.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        selJug.setText("Selección");

        modifJug.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        modifJug.setText("Modificación");

        delJug.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        delJug.setText("Eliminación");

        selPart.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        selPart.setText("Selección");

        selEst.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        selEst.setText("Selección");

        insertPart.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        insertPart.setText("Inserción");

        insertEst.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        insertEst.setText("Inserción");

        modifPart.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        modifPart.setText("Modificación");

        delPart.setFont(new java.awt.Font("Calibri Light", 0, 13)); // NOI18N
        delPart.setText("Eliminación");

        jLabel6.setFont(new java.awt.Font("Calibri Light", 1, 10)); // NOI18N
        jLabel6.setText("Seleccionar Usuario:");

        jLabel7.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel7.setText("Nombre de Usuario:");

        cmbUser.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnAsignar.setBackground(new java.awt.Color(255, 255, 255));
        btnAsignar.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        btnAsignar.setText("Asignar Permiso");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        txtCancelar.setBackground(new java.awt.Color(255, 255, 255));
        txtCancelar.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        txtCancelar.setText("Cancelar");
        txtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnAsignar)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(selEst)
                                        .addGap(18, 18, 18)
                                        .addComponent(insertEst))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(selPart)
                                        .addGap(18, 18, 18)
                                        .addComponent(insertPart)
                                        .addGap(18, 18, 18)
                                        .addComponent(modifPart)
                                        .addGap(18, 18, 18)
                                        .addComponent(delPart))
                                    .addGroup(panelLayout.createSequentialGroup()
                                        .addComponent(selJug)
                                        .addGap(18, 18, 18)
                                        .addComponent(insertJug)
                                        .addGap(18, 18, 18)
                                        .addComponent(modifJug)
                                        .addGap(18, 18, 18)
                                        .addComponent(delJug))))
                            .addGroup(panelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(txtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel6)
                    .addGroup(panelLayout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jLabel6)
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(insertJug)
                    .addComponent(selJug)
                    .addComponent(modifJug)
                    .addComponent(delJug))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(selPart)
                    .addComponent(insertPart)
                    .addComponent(modifPart)
                    .addComponent(delPart))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(selEst)
                    .addComponent(insertEst))
                .addGap(18, 18, 18)
                .addGroup(panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignar)
                    .addComponent(txtCancelar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_txtCancelarActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed

         Procesos sql=new Procesos();                                                                      
        
        if(selJug.isSelected()==true)
        {
            String sentenciaJ1="GRANT SELECT ON C##JOEL.JUGADOR TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaJ1);
        }
        if(insertJug.isSelected()==true)
        {
            String sentenciaJ2="GRANT INSERT ON C##JOEL.JUGADOR TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaJ2);
        }
        if(modifJug.isSelected()==true)
        {
            String sentenciaJ3="GRANT UPDATE ON C##JOEL.JUGADOR TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaJ3);
        }
        if(delJug.isSelected()==true)
        {
            String sentenciaJ4="GRANT DELETE ON C##JOEL.JUGADOR TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaJ4);
        }
        //--------------------------------------------------------------------------------------------------
        if(selPart.isSelected()==true)
        {
            String sentenciaP1="GRANT SELECT ON C##JOEL.PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP1);
            String sentenciaP12="GRANT SELECT ON C##JOEL.DETALLE_PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP12);
        }
        if(insertPart.isSelected()==true)
        {
            String sentenciaP2="GRANT INSERT ON C##JOEL.PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP2);
            String sentenciaP22="GRANT INSERT ON C##JOEL.DETALLE_PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP22);
        }
        if(modifPart.isSelected()==true)
        {
            String sentenciaP3="GRANT UPDATE ON C##JOEL.PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP3);
            String sentenciaP32="GRANT UPDATE ON C##JOEL.DETALLE_PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP32);
        }
        if(delPart.isSelected()==true)
        {
            String sentenciaP4="GRANT DELETE ON C##JOEL.PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP4);
            String sentenciaP42="GRANT DELETE ON C##JOEL.DETALLE_PARTIDO TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaP42);
        }
        //--------------------------------------------------------------------------------------------------
        if(selEst.isSelected()==true)
        {
            String sentenciaE1="GRANT SELECT ON C##JOEL.ESTADISTICAS TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaE1);
        }
        if(insertEst.isSelected()==true)
        {
            String sentenciaE2="GRANT INSERT ON C##JOEL.ESTADISTICAS TO "+cmbUser.getSelectedItem().toString();
            sql.ingresarDatos(estSQL, sentenciaE2);
        }
       JOptionPane.showMessageDialog(null, "Permisos Asignados Exitosamente.");  
    }//GEN-LAST:event_btnAsignarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAsignar;
    private javax.swing.JComboBox cmbUser;
    private javax.swing.JCheckBox delJug;
    private javax.swing.JCheckBox delPart;
    private javax.swing.JCheckBox insertEst;
    private javax.swing.JCheckBox insertJug;
    private javax.swing.JCheckBox insertPart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JCheckBox modifJug;
    private javax.swing.JCheckBox modifPart;
    private javax.swing.JPanel panel;
    private javax.swing.JCheckBox selEst;
    private javax.swing.JCheckBox selJug;
    private javax.swing.JCheckBox selPart;
    private javax.swing.JButton txtCancelar;
    // End of variables declaration//GEN-END:variables
}
