/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Partido;

import Principal.Login;
import Principal.Procesos;
import java.awt.Dimension;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author JL
 */
public class Consultas_Partido extends javax.swing.JFrame {

    /**
     * Creates new form Consultas_Partido
     */
    public static Statement estSQL=Login.estSQL;
    DefaultTableModel modelo=null;
    public Consultas_Partido() 
    {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ventana Estadísticas del Partido");
        this.setResizable(false);
        insertImage();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Img/icono.png"));
        setIconImage(icon);
        cerrar();
        
        
        String cabecera[]={};
        String datos[][]={};
        modelo=new DefaultTableModel(datos,cabecera);
        TablaPartidos.setModel(modelo); 
        cargarComboPartido();
        cargarComboEstado();
    }
    public void insertImage()
    {
        ImagePanel Imagen = new ImagePanel();
        panelMain.add(Imagen);
        panelMain.repaint();
    }
    public class ImagePanel extends JPanel 
    {
        public ImagePanel()
        {
            //Se crea un método cuyo parámetro debe ser un objeto Graphics
            this.setSize(725,690);
        }
        @Override
        public void paint(Graphics grafico)
        {
            Dimension height = getSize();
            //Se selecciona la imagen que tenemos en el paquete de la //ruta del programa
            ImageIcon Img = new ImageIcon(getClass().getResource("/Img/fondoMain2.jpg")); 
            //se dibuja la imagen que tenemos en el paquete Images //dentro de un panel
            grafico.drawImage(Img.getImage(), 0, 0, height.width, height.height, null);
            setOpaque(false);
            super.paintComponent(grafico);
        }
    }
    public void cerrar()
    {
        try
        {
            this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
            addWindowListener(new WindowAdapter ()
            {
                public void windowClosing(WindowEvent e)
                {
                    dispose();
                }
            });        
        this.setVisible(true);
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }
     public void editarCabecera()
    {
        JTableHeader th; 
        th = TablaPartidos.getTableHeader(); 
        Font fuente = new Font("Consolas", Font.BOLD, 12); 
        th.setFont(fuente); 
    }
    public void limpiarTabla(JTable tabla)
    {
        while(tabla.getRowCount()>0)
        {
            ((DefaultTableModel) tabla.getModel()).removeRow(0);
        }
    }
     public void cargarComboPartido()
    {
        cmbPartido.removeAllItems();
        
        Procesos sql=new Procesos();
        ResultSet rs=sql.consultarDatos(estSQL, "select id_partido from C##JOEL.partido");
        sql.buscarDatosCombo(rs, cmbPartido);
        
    }
     public void cargarComboEstado()
     {
         cmbEstado.removeAllItems();
         cmbEstado.addItem("Partido Ganado");
         cmbEstado.addItem("Partido Perdido");
         cmbEstado.addItem("Partido Empatado");
     }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        panelMain = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPartidos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        cmbPartido = new javax.swing.JComboBox();
        radio1 = new javax.swing.JRadioButton();
        radio2 = new javax.swing.JRadioButton();
        radio3 = new javax.swing.JRadioButton();
        jLabel3 = new javax.swing.JLabel();
        cmbEstado = new javax.swing.JComboBox();
        radio4 = new javax.swing.JRadioButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Calibri Light", 0, 28)); // NOI18N
        jLabel1.setText("Información Acerca de Partidos Jugados");

        TablaPartidos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaPartidos);

        jLabel2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel2.setText("Seleccionar Id. Partido: ");

        cmbPartido.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        cmbPartido.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(radio1);
        radio1.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        radio1.setText("Resultados de Partidos Jugados");
        radio1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                radio1FocusLost(evt);
            }
        });
        radio1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                radio1MouseReleased(evt);
            }
        });

        buttonGroup1.add(radio2);
        radio2.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        radio2.setText("Jugadores que Actuaron en el Partido");
        radio2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                radio2FocusLost(evt);
            }
        });
        radio2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio2MouseClicked(evt);
            }
        });

        buttonGroup1.add(radio3);
        radio3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        radio3.setText("Número de Partidos según Estado");
        radio3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                radio3FocusLost(evt);
            }
        });
        radio3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio3MouseClicked(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        jLabel3.setText("Estado: ");

        cmbEstado.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        cmbEstado.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        buttonGroup1.add(radio4);
        radio4.setFont(new java.awt.Font("Calibri Light", 0, 14)); // NOI18N
        radio4.setText("Rivales, Fecha,Hora, Lugar y Resultado del Partido");
        radio4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                radio4FocusLost(evt);
            }
        });
        radio4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                radio4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelMainLayout = new javax.swing.GroupLayout(panelMain);
        panelMain.setLayout(panelMainLayout);
        panelMainLayout.setHorizontalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMainLayout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(panelMainLayout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(radio2)
                                .addComponent(radio1)
                                .addGroup(panelMainLayout.createSequentialGroup()
                                    .addComponent(radio3)
                                    .addGap(34, 34, 34)
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(radio4)))
                        .addGap(32, 204, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMainLayout.createSequentialGroup()
                        .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelMainLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addContainerGap())))
        );
        panelMainLayout.setVerticalGroup(
            panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbPartido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radio1)
                .addGap(18, 18, 18)
                .addComponent(radio2)
                .addGap(18, 18, 18)
                .addGroup(panelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radio3)
                    .addComponent(jLabel3)
                    .addComponent(cmbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(radio4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void radio1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio1MouseReleased
        limpiarTabla(TablaPartidos);
        Procesos sql=new Procesos();
        
        ResultSet rs=sql.consultarDatos(estSQL, "select * from C##JOEL.partido\n" +
        "where id_partido='"+cmbPartido.getSelectedItem().toString()+"'--Cambiar por Partido");
        sql.procesarRB(rs, modelo);
        editarCabecera();  
    }//GEN-LAST:event_radio1MouseReleased

    private void radio2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio2MouseClicked
        limpiarTabla(TablaPartidos);
        Procesos sql=new Procesos();
        
        ResultSet rs=sql.consultarDatos(estSQL, "select nombres_jugador,apellidos_jugador,num_camiseta,posicion\n" +
        "from C##JOEL.detalle_partido,C##JOEL.jugador\n" +
        "where id_partido='"+cmbPartido.getSelectedItem().toString()+"'\n" +
        "and detalle_partido.cod_jugador=jugador.cod_jugador");
        sql.procesarRB(rs, modelo);
        editarCabecera();  
    }//GEN-LAST:event_radio2MouseClicked

    private void radio3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio3MouseClicked
        limpiarTabla(TablaPartidos);
        Procesos sql=new Procesos();
        int estado=-1;
        if(cmbEstado.getSelectedIndex()==0)
        {
            estado=1;
        }
        if(cmbEstado.getSelectedIndex()==1)
        {
            estado=0;
        }
        if(cmbEstado.getSelectedIndex()==2)
        {
            estado=2;
        }
        
        
        ResultSet rs=sql.consultarDatos(estSQL, "select count(*) as Cantidad_Estado\n" +
        "from C##JOEL.partido\n" +
        "where estado_partido="+estado);
        sql.procesarRB(rs, modelo);
        editarCabecera();  
    }//GEN-LAST:event_radio3MouseClicked

    private void radio1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio1FocusLost
        limpiarTabla(TablaPartidos);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_radio1FocusLost

    private void radio2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio2FocusLost
         limpiarTabla(TablaPartidos);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_radio2FocusLost

    private void radio3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio3FocusLost
         limpiarTabla(TablaPartidos);
        buttonGroup1.clearSelection();
        
    }//GEN-LAST:event_radio3FocusLost

    private void radio4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_radio4MouseClicked
        limpiarTabla(TablaPartidos);
        Procesos sql=new Procesos();
        
        ResultSet rs=sql.consultarDatos(estSQL, "select nombre_equipo_rival,fecha_hora,lugar,estadio,resultado from C##JOEL.partido\n" +
        "where id_partido='"+cmbPartido.getSelectedItem().toString().trim()+"'");
        sql.procesarRB(rs, modelo);
        editarCabecera(); 
    }//GEN-LAST:event_radio4MouseClicked

    private void radio4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_radio4FocusLost
        limpiarTabla(TablaPartidos);
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_radio4FocusLost

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPartidos;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.JComboBox cmbEstado;
    private javax.swing.JComboBox cmbPartido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JPanel panelMain;
    private javax.swing.JRadioButton radio1;
    private javax.swing.JRadioButton radio2;
    private javax.swing.JRadioButton radio3;
    private javax.swing.JRadioButton radio4;
    // End of variables declaration//GEN-END:variables
}
